config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'diabetics#index'
   resources :diabetics

  match 'reports/report', via: [:get, :post]

end

app/models/diabetic.rb
class Diabetic < ActiveRecord::Base
  belongs_to :user
  
  validates_numericality_of :glucose_level , :only_integer => true,  
    :greater_than_or_equal_to => 0,
    :less_than_or_equal_to => 9,
    :message => "Please enter single digit integer value."


  validate :user_quota, :on => :create  
   
  scope :current_user, -> (user_id){where(:user_id => user_id)} 
  
  def self.daily_report user_id
    daily_report_min = Diabetic.where(:user_id => user_id).group("date_format(created_at, '%m%d')").minimum(:glucose_level)
    daily_report_max = Diabetic.where(:user_id => user_id).group("date_format(created_at, '%m%d')").maximum(:glucose_level)
    daily_report_avg = Diabetic.where(:user_id => user_id).group("date_format(created_at, '%m%d')").average(:glucose_level)
    return daily_report_min,daily_report_max,daily_report_avg
  end

  def self.month_to_date_report end_date,user_id
    month_to_date=[]
    month_to_date << Diabetic.where(:user_id => user_id).where(:created_at => (end_date.beginning_of_month..end_date)).minimum(:glucose_level)
    month_to_date << Diabetic.where(:user_id => user_id).where(:created_at => (end_date.beginning_of_month..end_date)).maximum(:glucose_level)
    month_to_date << Diabetic.where(:user_id => user_id).where(:created_at => (end_date.beginning_of_month..end_date)).average(:glucose_level)
    month_to_date
  end

  def self.monthly_report user_id
    monthly_report_min = Diabetic.where(:user_id => user_id).group("date_format(created_at, '%M')").minimum(:glucose_level)
    monthly_report_max = Diabetic.where(:user_id => user_id).group("date_format(created_at, '%M')").maximum(:glucose_level)
    monthly_report_avg = Diabetic.where(:user_id => user_id).group("date_format(created_at, '%M')").average(:glucose_level)
    return monthly_report_min,monthly_report_max,monthly_report_avg
  end

  private 
    def user_quota
   	  daily_limit = Diabetic.where("user_id = ?", self.user_id).where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now)).to_a
      if daily_limit.count > 3
        errors.add(:base, "Exceeds daily limit. You can enter only 4 times in a day")
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :diabetics 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/diabetics_controller.rb
class DiabeticsController < ApplicationController
  before_filter :authenticate_user!
	def index
	  @diabetics = Diabetic.current_user(current_user.id)
  end

  def new
  	@diabetic= Diabetic.new
  end

	def create
    @diabetic= Diabetic.new(diabetic_params)
    if @diabetic.save
      redirect_to diabetics_path, alert: "Saved successfully"
    else
      render 'new'
    end    
  end

	private
    def diabetic_params
      params.require(:diabetic).permit( :glucose_level, :user_id )
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def report
    if request.post?
      if params[:report_type]=="Daily Report"
        @report =Diabetic.daily_report current_user.id

      elsif params[:report_type]=="Month to Date report"
        @report= Diabetic.month_to_date_report params[:end_date].to_date, current_user.id
      
      else
        @report=Diabetic.monthly_report current_user.id
      end
    else
    #get request code
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title)
    content_for :page_title do
      title
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger" 
      when :error, :validation_errors
        "alert-error"  
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
end
  

app/helpers/diabetics_helper.rb
module DiabeticsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/diabetics/index.html.erb
<% page_title "Home" %>
<h1 align ='center'> List of All Blood Glucose Level</h1>
<br/>
<h4><%= link_to 'New Entry', new_diabetic_path %> <%= link_to 'View Reports',reports_report_path %></h4>

<br/><br/>  

<table class = 'table table-bordered jumbotron'> 
  <tr>
    <th class = 'row col-md-2'> Glucose Level </th>
    <th class = 'row col-md-2'>  Time</th>
  </tr>

  <% if @diabetics.present? %>
    <% @diabetics.each do |f| %>
      <tr>
        <td ><%= f.glucose_level %> </td>
         <td ><%= f.created_at %> </td>
      </tr>
    <% end %>		
  <% end %>
</table>

<ul class="pager">
  <li class="previous"><a href="#">Previous</a></li>
  <li class="next"><a href="#">Next</a></li>
</ul>

app/views/diabetics/new.html.erb
<h1 align = 'center'> Please Enter your Blood Glucose Level </h1>

<% if @diabetic.errors.any? %>
  <h3>Please see the below errors</h3>
  <ul>
  <% @diabetic.errors.full_messages.each do |msg| %>
  <li ><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<div class = "jumbotron">
  <%= form_for @diabetic do |f| %>
    <p>
      <%= f.label :glucose_level %>
      <%= f.text_field :glucose_level %>

    </p>
   
    <h2> <%=f.hidden_field :user_id, :value => current_user.id %> </h2>
    <p>
      <%=  f.submit class: 'btn btn-primary' %>
    </p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiabeticSolution<%= "::#{yield :page_title}" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body >
   <nav class="navbar navbar-inverse">
    <% if user_signed_in? %>
      <p> Welcome <%= current_user.email %><%= link_to "Sign Out", destroy_user_session_path,  method: :get %> </p>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path ,class: 'glyphicon glyphicon-search'%>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </nav>
   
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
<% end %>

  <%= yield %>
  
  </body>
</html>

app/views/reports/report.html.erb
<h1> View Reports</h1>

<%= form_tag reports_report_path do %>
Please select Report Type  <%= select_tag :report_type, options_for_select(["Daily Report", "Month to Date report","Monthly Report"]) %>

<%= text_field_tag :end_date, "", class: 'datepicker' %>

<%= submit_tag "View Reports" %>

<% end %>
<script>
  $(function() {
    $('.datepicker').datepicker({ dateFormat: 'dd-mm-yy' });
  });
</script>